[package]
name = "orecchiette-sdr-usrp-rs"
license = "GPL-3.0-or-later"
version = "0.1.5"
edition = "2024"
description = "USRP (B210 / B205mini) implementation of the SdrSource trait."
repository = "https://github.com/isaacbentley/orecchiette-sdr-usrp-rs"
readme = "README.md"
keywords = ["sdr", "usrp", "ettus", "rf", "iq"]
categories = ["hardware-support", "api-bindings"]

[dependencies]
orecchiette-sdr-source-rs = "0.1.3"
# TODO(dependabot): uhd-sys 0.1.3 (pulled by uhd 0.3.0+) pins bindgen 0.55.1 which brings in vulnerable 
# versions of atty and shlex via build-dependencies. These alerts are currently dismissed on GitHub 
# as tolerable risk since they don't ship in the binary. If samcrow/uhd-rust ever bumps bindgen, 
# we should remove this exception.
uhd = "0.4.0"
crossbeam = "0.8"
num-complex = "0.4"
anyhow = "1.0"
tracing = "0.1"
